In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Marlon\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [2]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [3]:
np.array(a)
print(type(np.array(a)))

<class 'numpy.ndarray'>


In [4]:
a

[1, 2, 3, 4, 5]

In [5]:
np.array(a,dtype="float64")
a
print(type(a))

<class 'list'>


In [6]:
print(np.zeros(5, dtype="int"))

[0 0 0 0 0]


In [9]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(np.full((3,4),500))

[[500 500 500 500]
 [500 500 500 500]
 [500 500 500 500]]


In [13]:
print(np.random.random((3,3)))
#seed allows reproducibility

[[0.64690872 0.13909128 0.39776874]
 [0.05267655 0.55076097 0.91278323]
 [0.04314038 0.36170578 0.59991694]]


In [15]:
np.random.seed(5)
print(np.random.random((3,3)))

[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005 ]]


In [16]:
print(np.random.random((3,3)))

[[0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703]
 [0.27408646 0.41423502 0.29607993]]


In [17]:
np.random.seed(5)
print(np.random.random((3,3)))

[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005 ]]


In [18]:
#normal distribution (mean, std dev, row, col)
print(np.random.normal(0,1,(3,3)))

[[-0.40309331  1.63762849 -0.60529785]
 [-1.59441507  0.91187364 -1.44384155]
 [ 1.82444017  1.45762512 -0.91025815]]


In [20]:
#identity matrix( 1 diagonal, other elements 0, equal number of rows and cols)

print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [37]:
#create a 10-length zero integer
print(np.zeros(10, dtype="int"))

[0 0 0 0 0 0 0 0 0 0]


In [25]:
#one 3*4 integer
print(np.ones((3,4), dtype="float"))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
#3x5 3.14
np.full((3,5), 3.14)


array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [35]:
#create linear sequence from 0 to 20 jumping every 2
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
#create an array of 5 values evenly spaced from 0 to 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
#Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.25358821, 0.32756395, 0.1441643 ],
       [0.16561286, 0.96393053, 0.96022672],
       [0.18841466, 0.02430656, 0.20455555]])

In [40]:
#Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.99001894,  0.99643983,  0.71242127],
       [ 0.05914424, -0.36331088,  0.00328884],
       [-0.10593044,  0.79305332, -0.63157163]])

In [44]:
#Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10, (3,3))

array([[9, 5, 7],
       [0, 9, 6],
       [0, 5, 2]])

In [45]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# Creating a one dimensional array.
one=np.random.randint(10, size=6)
one

array([8, 6, 8, 0, 5, 2])

In [53]:
# Creating a two dimensional array.
two=np.random.randint(10, size=(2,5))
two

array([[0, 7, 7, 6, 0],
       [0, 8, 5, 5, 9]])

In [54]:
# Creating a three dimensional array.
three=np.random.randint(10, size=(3,4,5))
three

array([[[6, 4, 5, 2, 8],
        [8, 1, 6, 3, 4],
        [1, 8, 0, 2, 2],
        [4, 1, 6, 3, 4]],

       [[3, 1, 4, 2, 3],
        [4, 9, 4, 0, 6],
        [6, 9, 2, 9, 3],
        [0, 8, 8, 9, 7]],

       [[4, 8, 6, 8, 0],
        [5, 3, 4, 0, 2],
        [2, 1, 1, 7, 1],
        [7, 2, 6, 3, 6]]])

In [61]:

# Using the attributes to determine the dimension of the arrays.
print("one ==>", one.ndim)
print("two ==>", two.ndim)
print("three ==>", three.ndim)

one ==> 1
two ==> 2
three ==> 3


In [63]:
#Using the attribute to determine the shape of the arrays.
print("one ==>", one.shape)
print("two ==>", two.shape)
print("three ==>", three.shape)

one ==> (6,)
two ==> (2, 5)
three ==> (3, 4, 5)


In [64]:
# Using the attribute to determine the size of the arrays or total number of elements
print("one ==>", one.size)
print("two ==>", two.size)
print("three ==>", three.size)

one ==> 6
two ==> 10
three ==> 60


In [66]:

# Using the attribute to determine the datatype of the arrays.

print("one ==>", one.dtype)
print("two ==>", two.dtype)
print("three ==>", three.dtype)

one ==> int32
two ==> int32
three ==> int32


In [68]:
# Array Indexing: Accessing Single Elements
print(one[2])
one

8


array([8, 6, 8, 0, 5, 2])

In [80]:

# Accessing the elements in a multi dimensional array

two[1,2]

5

In [84]:

# Changing the values of the array

one
one[0]=9
one
one[0]=1.99
one

array([1, 6, 8, 0, 5, 2])

In [94]:
# Array Slicing: Accessing Subarrays
# The syntax of the slicing is ==> x[start:stop:step] ==> default value is:
# [0: size of the dimension: 1]

a=np.random.randint(10, size=(10))
a


array([4, 4, 9, 9, 6, 7, 9, 6, 0, 7])

In [96]:
a[0:5:2]


array([4, 9, 6])

In [99]:
a[::-1]

array([7, 0, 6, 9, 7, 6, 9, 9, 4, 4])

In [101]:
two
two[1,1]=9
two

array([[0, 7, 7, 6, 0],
       [0, 9, 5, 5, 9]])

In [117]:
# Modifing the array with using copy() function.
two
copy2=two[:2,:2].copy()
copy2[0,1]=6
copy2
two

array([[0, 7, 7, 6, 0],
       [0, 9, 5, 5, 9]])

In [119]:
# Reshaping of Arrays using reshape() in a more advanced way

grid=np.arange(1,21).reshape(4,5)
grid

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [136]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate([a,b])
c
d=np.array([7,8,9])
e=np.concatenate([c,d])
e
two
f=np.concatenate([two,two], axis=1)
f

array([[0, 7, 7, 6, 0, 0, 7, 7, 6, 0],
       [0, 9, 5, 5, 9, 0, 9, 5, 5, 9]])

In [138]:
np.vstack([one, one])
np.hstack([one,one])

array([1, 6, 8, 0, 5, 2, 1, 6, 8, 0, 5, 2])

In [144]:
a= np.arange(1,21)
b,c,d=np.split(a, [3,6])
b,c,d

(array([1, 2, 3]),
 array([4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [145]:
grid=a.reshape(4,5)
grid


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [152]:
left, tight=np.hsplit(grid,[2])
left

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [154]:
x=np.arange(4)
x
print
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print(np.add(x, 2))

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[2 3 4 5]


In [157]:
neg=np.array([-1,-2,-3])
neg
print(np.abs(neg))

[1 2 3]


In [165]:
#trigonometric functions

x=np.linspace(0,np.pi,3)
x
print(x)
print(np.cos(x))
print(np.sin(x))
print(np.tan(x))

y=[-1,0,1]
print(np.arcsin(y))
print(np.arccos(y))
print(np.arctan(y))

[0.         1.57079633 3.14159265]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[-1.57079633  0.          1.57079633]


In [177]:
#exponents and logarithms

x=[1,2,3]
x
np.exp(x)
np.exp2(x)
np.power(3,x)

y=[1,2,4,10]
y
np.log(y)
np.log2(y)
np.log10(y)


array([0.        , 0.30103   , 0.60205999, 1.        ])

In [190]:
# Another excellent source for more specialized and obscure ufuncs is the submodule
# scipy.special. If you want to compute some obscure mathematical function on
# your data, chances are it is implemented in scipy.special.

from scipy import special
x=[1,5,10]

print(special.gamma(x))
print(special.beta(x,2))
print(special.gammaln(x))
print(special.erf(x)) #error function, inverse, complement
print(special.erfc(x))

[1.0000e+00 2.4000e+01 3.6288e+05]
[0.5        0.03333333 0.00909091]
[ 0.          3.17805383 12.80182748]
[0.84270079 1.         1.        ]
[1.57299207e-01 1.53745979e-12 2.08848758e-45]


In [202]:
# Advanced Ufunc Features
# Specifying output

x=np.arange(5)
y=np.empty(5)
np.add(x,10,out=y)
y

w=np.zeros(10)
print(w)
print(x)
np.power(2,x, out=w[::2])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4]


array([ 1.,  2.,  4.,  8., 16.])

In [211]:
#aggregates
x=np.arange(1,6)
print(x)
print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))


[1 2 3 4 5]
15
[ 1  3  6 10 15]
120
[  1   2   6  24 120]


In [214]:
#sorting
a = np.array([1, 9, 0, 7, 3, 5])
sort=np.sort(a)
print(sort)

#sortedindex
print(np.argsort(a))

[0 1 3 5 7 9]
[2 0 4 5 3 1]


In [224]:
# partitioning
# NumPy provides this in the np.partition function. 
# np.partition takes an array and a number K; the result is a new array with the smallest K values to the left of the partition,
# and the remaining values to the right, in arbitrary order:
x = np.array([7, 12, 13, 10, 60, 500, 14]) 
print(np.partition(x,2))


[  7  10  12  13  60 500  14]
